spring.application.name=cra-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cra_backend_api?autoReconnect=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


#JWT config
jwt.secret =404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=360000